In [2]:
import numpy as np
import matplotlib.pyplot as plt
from qpmr.quasipoly.core import _eval_array

In [15]:
delays = np.array([0.0, 0.45])
coefs = np.array([[0, 1],[1, 0]])
matlab_roots = np.array([-0.3181 + 1.3372j,
                         -2.0623 + 7.5886j,
                         -2.6532 +13.9492j,
                         -3.0202 +20.2725j,
                         -3.2878 +26.5805j,])

In [80]:
np.random.seed(40)
s = np.random.rand(5,5) + 1j * np.ones(shape=(5,5))

In [81]:
r1 = _eval_array(coefs, delays, s)

In [82]:
def _eval_array_opt(coefs, delays, s):
    _memory = np.ones_like(s)
    # solve degree 0
    dels = np.exp(- s[..., np.newaxis] * delays[np.newaxis, ...])
    result = np.sum(dels * coefs[:, 0], -1)
    print(_memory)
    print(result)
    print(20*"-")
    for d in range(1, coefs.shape[1]): # solve other degrees
        _memory *= s # elementwise multiplication
        result += np.multiply(_memory, np.sum(dels * coefs[:, d], -1))
        print(_memory)
        print(result)
        print(f"{s=}")
        print(20*"-")
    return result

In [83]:
r2 = _eval_array_opt(coefs, delays, s)

[[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]]
[[0.74951944-0.36205916j 0.87828988-0.42426238j 0.63147018-0.30503487j
  0.79124218-0.38221354j 0.73526697-0.35517443j]
 [0.7853511 -0.37936783j 0.71053033-0.34322528j 0.68005653-0.32850475j
  0.63482062-0.30665331j 0.6612174 -0.31940441j]
 [0.57909639-0.27973544j 0.68713046-0.33192185j 0.62428412-0.30156361j
  0.65458477-0.31620049j 0.88935885-0.4296093j ]
 [0.59942519-0.28955537j 0.73541446-0.35524568j 0.85352542-0.41229978j
  0.61832014-0.29868267j 0.82211453-0.39712659j]
 [0.83255578-0.40217029j 0.73566528-0.35536684j 0.66612928-0.32177712j
  0.58526329-0.2827144j  0.61886766-0.29894716j]]
--------------------
[[0.40768703+1.j 0.05536604+1.j 0.78853488+1.j 0.28730518+1.j
  0.45035059+1.j]
 [0.30391231+1.j 0.52639952+1.j 0.62381221+1.j 0.77677546+1.j
  0.68624165+1.j]
 [0.98093886+1.j 0.60081609

In [84]:
r1 - r2

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [59]:
_memory = np.ones_like(s)
# solve degree 0
dels = np.exp(- s[..., np.newaxis] * delays[np.newaxis, ...])


In [62]:
dels * coefs[:, 0]

array([[0.        +0.j        , 0.74951944-0.36205916j],
       [0.        +0.j        , 0.87828988-0.42426238j],
       [0.        +0.j        , 0.63147018-0.30503487j],
       [0.        +0.j        , 0.79124218-0.38221354j],
       [0.        +0.j        , 0.73526697-0.35517443j]])

In [63]:
dels

array([[1.        -0.j        , 0.74951944-0.36205916j],
       [1.        -0.j        , 0.87828988-0.42426238j],
       [1.        -0.j        , 0.63147018-0.30503487j],
       [1.        -0.j        , 0.79124218-0.38221354j],
       [1.        -0.j        , 0.73526697-0.35517443j]])

In [ ]:
result = np.sum(dels * coefs[:, 0], axis=-1)
print(result)
for d in range(1, coefs.shape[1]): # solve other degrees
    _memory *= s # elementwise multiplication
    dels = np.exp(- _memory[..., np.newaxis] * delays[np.newaxis, ...])
    result += np.sum(dels * coefs[:, [d]].T, -1)