In [1]:
import numpy as np

In [4]:
a = np.random.rand(3,5)

In [6]:
mask = a > 0.8

In [7]:
mask

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False,  True, False]])

In [9]:
(~mask).all(axis=0)

array([False,  True,  True, False,  True])

In [32]:
col_mask = np.array([False, True, True, False, True, False, False, False, True, False, True])

In [33]:
last_valid_col = len(col_mask) - np.argmax(col_mask[::-1]) # col_mask = [True, False, True, False, False] -> 2

In [34]:
last_valid_col

np.int64(11)

In [35]:
np.argmax(col_mask[::-1])

np.int64(0)

In [36]:
col_mask[:-np.argmax(col_mask[::-1])] = True
col_mask[-np.argmax(col_mask[::-1]):] = False
col_mask

array([False, False, False, False, False, False, False, False, False,
       False, False])