In [36]:
import numpy as np
import qpmr.quasipoly
coefs = np.array([[0., 1], [0, 1]])
delays = np.array([0., 1])
ccoefs, ddelays = qpmr.quasipoly.shift(coefs, delays, 1)

In [37]:
ccoefs

array([[-1.        ,  1.        ],
       [-2.71828183,  2.71828183]])

In [38]:
ddelays

array([0., 1.])

In [40]:
a, b = qpmr.quasipoly.shift(ccoefs, ddelays, -1)

In [41]:

a

array([[0., 1.],
       [0., 1.]])